### ISSUE TITLE
Update provider package

### ISSUE THREAD

**Issue by suragch** [FilledStacks/provider_architecture#8]
The provider package that package depends on is now version 4.0.1. I don't know if that makes a difference for any of the code, but I generally like to use the most up to date packages.

**Comment by sam-androiddev** [comment]
Cannot use provider_architecture 1.0.3 with latest provider package. I am getting an error:
Running "flutter pub get" in rovers_app...                      Because provider_architecture 1.0.3 depends on provider ^3.2.0 and no versions of provider_architecture match >1.0.3 <2.0.0, provider_architecture ^1.0.3 requires provider ^3.2.0.


So, because rovers_app depends on both provider ^4.0.1 and provider_architecture ^1.0.3, version solving failed.
pub get failed (1; So, because rovers_app depends on both provider ^4.0.1 and provider_architecture ^1.0.3, version solving failed.)

**Comment by FilledStacks** [comment]
I fixed this a few days ago and forgot to closet this.

**Comment by sam-androiddev** [comment]
Already using the updated version 1.0.5
You're the best. 👍
